//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpEgitimKampi301.EFProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCATION
    {
        public int LOCATIONID { get; set; }
        public string CITY { get; set; }
        public string COUNTRY { get; set; }
        public Nullable<byte> CAPACITY { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public string DAYNIGHT { get; set; }
        public Nullable<int> GUIDEID { get; set; }
    
        public virtual GUIDE GUIDE { get; set; }
    }
}
